EventCalendar/account/urls.py
# account/urls.py

from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from . import views

app_name = "account"
urlpatterns = [
    path("join", views.create, name="join"),
    # path("login", views.user_login, name="login"),
    path("login", 
        LoginView.as_view(
            template_name="account/login.html", # login form template
            form_class=AuthenticationForm       # Form class
        ),
        name="login"),
    path("logout", views.user_logout, name="logout"),
    path("detail", views.user_detail, name="detail"), 
    path("password_change", views.change_password, name="password_change"),
    path("update", views.user_update, name="update"),
    path("approve/<int:user_id>", views.approve_request, name="approve_request"),
    path("reject/<int:user_id>", views.reject_request, name="reject_request"),
    path("user_expel/", views.user_expel, name="user_expel"),
    path("delete", views.user_delete, name="delete"),
    path("team_delete/", views.user_team_delete, name="team_delete"),
]

EventCalendar/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('team_calendar/', include('team_calendar.urls')),
    path('account/', include('account.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

EventCalendar/team_calendar/urls.py
from django.urls import path
from . import views 

app_name = "team_calendar"

urlpatterns = [
    path('team_list/', views.team_list, name='team_list'),
    path('create_team/', views.create_team, name='create_team'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('delete_schedule/<int:schedule_id>/', views.delete_schedule, name='delete_schedule'),
    path('join_team/<str:team_name>/', views.join_team, name='join_team'),
    path('cancel_request/', views.cancel_request, name='cancel_request'),
]



EventCalendar/templates/home.html
<!-- templates/home.html -->
{% extends "layout.html"%}
<!-- layout.html을 확장해서 template을 구현. -->
<!-- block 을 재정의 -->
{% block title %}Home{% endblock title%}
{% block contents%}
<h1>환영합니다.</h1>
<h2>팀 일정관리 앱입니다.</h2>
{% endblock contents%}


EventCalendar/templates/layout.html
{% comment %}
여러 페이지의 틀(layout)이 되는 templates
    1. 공통적으로 들어가는 코드(html, css, js, template)를 작성.
    2. page마다 변경될 부분들은 block 지정. 
                    {%block  이름%}{%endblock 이름%}
    3. 개별 page들은 이 template을 확장해서 구현.
        block부분에 내용을 채워서 구현.
{% endcomment %}
{# layer.html #}
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}Document{%endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>   
{% comment %}
- 팀목록 {%url 'team_calendar:list'%}
- 팀만들기{% url 'team_calendar:team_create'%}
- 로그인 {% url 'account:login'%}
- 로그아웃 {% url 'account:logout'%}
- 회원님 {% url 'account:detail' %} {{user.name}}
- 회원 가입 {% url 'account:join'%}
{% endcomment%}
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="/" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'team_calendar:team_list'%}" class="nav-link">팀목록</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'team_calendar:create_team'%}" class="nav-link">팀등록</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:logout'%}" class="nav-link">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:detail' %}" class="nav-link"><b>{{user.name}} 님</b></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'account:join'%}" class="nav-link">가입</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:login'%}" class="nav-link">로그인</a>
                    </li>
                {% endif %}
                
            </ul>
        </div>
    </nav>
    <div class="container mt-4">
        {% block contents%}{% endblock contents%}
    </div>
</body>
</html>
