EventCalendar/account/urls.py
# account/urls.py

from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from . import views

app_name = "account"
urlpatterns = [
    path("join", views.create, name="join"),
    # path("login", views.user_login, name="login"),
    path("login", 
        LoginView.as_view(
            template_name="account/login.html", # login form template
            form_class=AuthenticationForm       # Form class
        ),
        name="login"),
    path("logout", views.user_logout, name="logout"),
    path("detail", views.user_detail, name="detail"), 
    path("password_change", views.change_password, name="password_change"),
    path("update", views.user_update, name="update"),
    path("approve/<int:user_id>", views.approve_request, name="approve_request"),
    path("reject/<int:user_id>", views.reject_request, name="reject_request"),
    path("user_expel/", views.user_expel, name="user_expel"),
    path("delete", views.user_delete, name="delete"),
    path("team_delete/", views.user_team_delete, name="team_delete"),
]

EventCalendar/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('team_calendar/', include('team_calendar.urls')),
    path('account/', include('account.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

EventCalendar/team_calendar/urls.py
from django.urls import path
from . import views 

app_name = "team_calendar"

urlpatterns = [
    path('team_list/', views.team_list, name='team_list'),
    path('create_team/', views.create_team, name='create_team'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('delete_schedule/<int:schedule_id>/', views.delete_schedule, name='delete_schedule'),
    path('join_team/<str:team_name>/', views.join_team, name='join_team'),
    path('cancel_request/', views.cancel_request, name='cancel_request'),
]



EventCalendar/team_calendar/models.py
from django.db import models
from account.models import User

# Create your models here.

class Team(models.Model):
    id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=50, unique=True)
    team_manager = models.CharField(max_length=50)
    member1 = models.CharField(max_length=50, default=None, null=True)
    member2 = models.CharField(max_length=50, default=None, null=True)
    member3 = models.CharField(max_length=50, default=None, null=True)

class CalendarData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    year = models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    memo = models.TextField(blank=True)

EventCalendar/team_calendar/forms.py
from django import forms
import datetime

class TimeForm(forms.Form):
    current_year = datetime.datetime.now().year
    YEARS = [(y, y) for y in range(current_year - 10, current_year + 10)]
    MONTHS = [(m, m) for m in range(1, 13)]
    
    year = forms.ChoiceField(choices=YEARS, initial=current_year)
    month = forms.ChoiceField(choices=MONTHS, initial=datetime.datetime.now().month)
    MINUTES = [(f'{h:02d}:{m:02d}', f'{h:02d}:{m:02d}') for h in range(24) for m in range(0, 60, 15)]
    start_time = forms.ChoiceField(choices=MINUTES)
    end_time = forms.ChoiceField(choices=MINUTES)
    selected_day = forms.CharField(widget=forms.HiddenInput)
    memo = forms.CharField(required=False)

EventCalendar/team_calendar/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
import calendar
from datetime import datetime
from .models import Team, CalendarData
from account.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import TimeForm
from django.contrib import messages

@login_required
def calendar_view(request):
    if not request.user.team:
        messages.warning(request, '권한이 없습니다.')
        return render(request, 'list.html')

    user_team = get_object_or_404(Team, team_name=request.user.team)

    if request.method == 'POST':
        form = TimeForm(request.POST)
        if form.is_valid():
            year = int(request.POST.get('year'))
            month = int(request.POST.get('month'))
            selected_day = int(form.cleaned_data['selected_day'])
            start_time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            start_time = datetime.strptime(start_time, '%H:%M').time()
            end_time = datetime.strptime(end_time, '%H:%M').time()
            memo = request.POST.get('memo')
            if not memo:
                memo = '비밀'
            CalendarData.objects.create(user=request.user, team=user_team, year=year, month=month, day=selected_day, start_time=start_time, end_time=end_time, memo=memo)
            return redirect(f'{request.path}?year={year}&month={month}')
    else:
        current_year = datetime.now().year
        current_month = datetime.now().month
        form = TimeForm(initial={'year': current_year, 'month': current_month})

    year = int(request.GET.get('year', datetime.now().year))
    month = int(request.GET.get('month', datetime.now().month))

    cal = calendar.Calendar()
    month_days = cal.monthdayscalendar(year, month)

    schedules = {}
    for schedule in CalendarData.objects.filter(team=user_team, year=year, month=month):
        if schedule.day not in schedules:
            schedules[schedule.day] = []
        schedules[schedule.day].append({
            'user_name' : schedule.user.name,
            'start_time': schedule.start_time.strftime('%H:%M'),
            'end_time': schedule.end_time.strftime('%H:%M'),
            'is_user_schedule': schedule.user == request.user,
            'id': schedule.id,
            'memo': schedule.memo
        })

    # ## 개당 스케쥴 6개 이하 정의본
    # for overday in schedules:
    #     if len(schedules[overday])>6:
    #         messages.warning(request, '일정은 6개까지 등록 가능합니다.')
    #         year = int(request.POST.get('year'))
    #         month = int(request.POST.get('month'))
    #         return redirect(f'{request.path}?year={year}&month={month}')

    context = {
        'calendar': month_days,
        'form': form,
        'minutes': [f'{h:02d}:{m:02d}' for h in range(24) for m in range(0, 60, 15)],
        'schedules': schedules.items(),
        'current_year': year,
        'current_month': month,
        'years': range(datetime.now().year - 10, datetime.now().year + 10),
        'months': range(1, 13),
    }
    return render(request, 'calendar.html', context)

@login_required
def delete_schedule(request, schedule_id):
    schedule = get_object_or_404(CalendarData, id=schedule_id)
    if schedule.user == request.user and schedule.team.team_name == request.user.team:
        schedule.delete()
    year = request.POST.get('year')
    month = request.POST.get('month')
    redirect_url = reverse("team_calendar:calendar_view")+f'?year={year}&month={month}'
    return HttpResponseRedirect(redirect_url)

def team_list(request):
    team_list = Team.objects.all()
    if request.user.is_authenticated:
        user_team = request.user.team
        user_request_to = request.user.request_to
    else:
        user_team = None
        user_request_to = None
    return render(request, "list.html", {"team_list":team_list, "user_team":user_team, "user_request_to":user_request_to, "login":request.user.is_authenticated})

@login_required
def create_team(request):
    if request.method == "GET":
        return render(request, "create_team.html")
    
    elif request.method == "POST":
        if not request.user.team:  # 사용자가 팀에 속해 있지 않은 경우
            team_name = request.POST.get("team_name")
            user_name = request.POST.get("user_name")  # 팀 매니저의 이름

            # 중복된 팀 이름 체크
            if Team.objects.filter(team_name=team_name).exists():
                messages.error(request, '이미 존재하는 팀 이름입니다. 다른 이름을 선택해주세요.')
                return render(request, "create_team.html")
            else:
                # 팀 생성 및 사용자 속성 업데이트
                team = Team(team_name=team_name, team_manager=user_name)
                team.save()

                user = request.user
                user.is_team_manager = True
                user.team_manager = True
                user.request_to = None
                user.team = team.team_name
                user.save()

                messages.success(request, '팀이 성공적으로 생성되었습니다.')
                return redirect(reverse("team_calendar:team_list"))
        
        else:
            messages.warning(request, '이미 가입한 팀이 있습니다.')

        return redirect(reverse("team_calendar:team_list"))
    
# 팀 참여 요청
@login_required
def join_team(request, team_name):
    user = request.user
    user.request_to = team_name
    user.save()
    url = reverse("team_calendar:team_list")
    return redirect(url)

# 팀 참여 요청 취소 
@login_required
def cancel_request(request):
    user = request.user
    user.request_to = None
    user.save()
    url = reverse("team_calendar:team_list")
    return redirect(url)


EventCalendar/team_calendar/templates/calendar.html
<!DOCTYPE html>
<html>
<head>
    <title>Calendar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .day-cell {
            height: 100px;
            text-align: center;
            vertical-align: top;
            cursor: pointer;
            position: relative;
            width : 185px;
        }
        .overloaded{
            height: 100px;
            text-align: center;
            vertical-align: top;
            cursor: pointer;
            position: relative;
            width : 185px;
        }
        .selected {
            background-color: #f8d7da !important;
        }
        .schedule-item {
            margin-top: 5px;
            font-size: 12px;
            display: flex;
            justify-content: space-evenly;
        }
        .sunday {
            color: red !important;
        }
        .saturday{
            color: blue !important;
        }
        .highlight{
            background-color: rgba(255, 0, 0, 0.2) !important;
        }
        
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="/" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'team_calendar:team_list'%}" class="nav-link">팀목록</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'team_calendar:create_team'%}" class="nav-link">팀등록</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:logout'%}" class="nav-link">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:detail' %}" class="nav-link"><b>{{user.name}} 님</b></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'account:join'%}" class="nav-link">가입</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:login'%}" class="nav-link">로그인</a>
                    </li>
                {% endif %}
                
            </ul>
        </div>
    </nav>
<div class="container">
    <form method="get" action="">
        <div class="row mb-3">
            <div class="col-md-3">
                <select name="year" class="form-select" id="yearSelect">
                    {% for year in years %}
                    <option value="{{ year }}" {% if year == current_year %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-3">
                <select name="month" class="form-select" id="monthSelect">
                    {% for month in months %}
                    <option value="{{ month }}" {% if month == current_month %}selected{% endif %}>{{ month }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-primary">보기</button>
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th class="sunday">Sun</th>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
            <th class="saturday">Sat</th>
        </tr>
        </thead>
        <tbody>
        {% for week in calendar %}
        <tr>
            {% for day in week %}
            <td class=" 
                {% for key, values in schedules %}
                    {% if day == key%}
                        highlight
                        {% if values|length >= 6%}
                            overloaded
                        {% else%}
                            day-cell
                        {% endif%}
                    {%else%}
                    day-cell
                    {% endif%}
                {%endfor%}
                "
                data-day="{{ day }}">
                {% if day != 0 %}
                <div class="{% if forloop.counter0 == 0 %}sunday{% elif forloop.counter0 == 6 %}saturday{% endif %}">
                    {{ day }}
                </div>
                {% else %}
                    <div class="inactive"></div>
                {% endif %}
                {% for key, values in schedules %}
                    {% if day == key%}
                        {%for schedule in values %}
                    <div class="schedule-item">
                        <span> {{schedule.user_name}} : {{ schedule.start_time }}~{{ schedule.end_time }} <br>사유:{{schedule.memo}}
                        </span>
                        {% if schedule.is_user_schedule %}
                            <form method="post" action="{% url 'team_calendar:delete_schedule' schedule.id %}" style="display: inline;" onsubmit="updateYearMonth()">
                                {% csrf_token %}
                                <input type="hidden" id="year" name="year" value="{{ current_year }}">
                                <input type="hidden" id="month" name="month" value="{{ current_month }}">
                                <button type="submit" class="btn-close" aria-label="Close" onclick="event.stopPropagation();"></button>
                            </form>
                        {% endif %}
                    </div>
                    {% endfor%}
                    {% endif %}
                {% endfor %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="timeModal" tabindex="-1" aria-labelledby="timeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="timeForm"  method="post" action="{% url 'team_calendar:calendar_view' %}" >
                <div class="modal-header">
                    <h5 class="modal-title" id="timeModalLabel">시간 선택</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="start_time" class="form-label">Start Time:</label>
                        <select id="start_time" name="start_time" class="form-select">
                            {% for minute in minutes %}
                            <option value="{{ minute }}">{{ minute }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="end_time" class="form-label">End Time:</label>
                        <select id="end_time" name="end_time" class="form-select">
                            {% for minute in minutes %}
                            <option value="{{ minute }}">{{ minute }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="memo" class="form-label">메모:</label>
                        <input type="text" id="memo" name="memo" class="form-control" placeholder="메모를 입력하세요">
                    </div>
                    <input type="hidden" id="selected_day" name="selected_day">
                    <input type="hidden" id="year" name="year" value="{{ current_year }}">
                    <input type="hidden" id="month" name="month" value="{{ current_month }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">등록</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.querySelectorAll('.day-cell').forEach(function(day) {
        day.addEventListener('click', function() {
            if (this.dataset.day !== "0")
            var modal = new bootstrap.Modal(document.getElementById('timeModal'));
            document.getElementById('selected_day').value = this.dataset.day;
            document.getElementById('year').value = document.getElementById('yearSelect').value;
            document.getElementById('month').value = document.getElementById('monthSelect').value;
            modal.show();
        });
    });

    document.querySelectorAll('.overloaded').forEach(function(day) {
        day.addEventListener('click', function() {
            alert("일정이 너무 많습니다");
        });
    });

    document.querySelectorAll('.btn-close').forEach(function(button) {
    button.addEventListener('click', function(event) {
        event.stopPropagation();
        });
    });

    function updateYearMonth() {
            document.getElementById('year').value = document.getElementById('yearSelect').value;
            document.getElementById('month').value = document.getElementById('monthSelect').value;
        }
    
    document.getElementById("timeForm").onsubmit = function(event) {
        event.preventDefault(); 
            if (time_valid()) {
            this.submit(); 
        }   
    };

    function time_valid(){
        var start_time = document.getElementById('start_time').value;
        var end_time = document.getElementById('end_time').value;
        if(start_time >= end_time){
            alert("시간 설정을 확인해 주세요.");
            return false;
        }
        else {
        return true;
        }
    }
</script>
</body>
</html>

EventCalendar/team_calendar/templates/create_team.html
{% extends "layout.html"%}
{%block title%}팀 등록{%endblock title%}
{%block contents%}
<h1>팀 등록</h1>
<!-- form의 action을 생략하면 현재 url경로로 요청.-->
<form method="post" onsubmit="return f_submit()">
    {% csrf_token %}
    <input type="hidden" name="user" value="{{user}}">
    <input type="hidden" name="user_name" value="{{user.name}}">
    <h2>팀 이름</h2>
    <input type="text" name="team_name" class="form-control" style="max-width:600px" required />
    <div class="mt-3">
        <button type="submit" class="btn btn-primary" id="submit">등록</button>
    </div>
</form>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% if  user.team  %}
<script>
    function f_submit() {
        alert("이미 소속된 팀이 있습니다.");
        return false
    }

    function name_check() {
        alert("중복된 팀이름 입니다.");
        return false
    }

</script>
    {% endif %}

{%endblock contents%}

EventCalendar/team_calendar/templates/list.html
{% extends "layout.html" %}
{% block title%}팀 목록{%endblock title%}
{%block contents%}

<h1>팀 목록</h1>
<div class="list-group mt-4" style="max-width:600px">
    <!-- 유저가 팀 있을시 -->
    {% if user_team %}
    <a href="{% url 'team_calendar:calendar_view'%}" class="list-group-item list-group-item-action">
        <b>My Team : {{user_team|truncatewords:5}}</b>
        {% for team in team_list %}
            {% if team.team_name == user_team %}
        <li>팀장 : {{ team.team_manager  }}</li>
            {% endif %}
        {% endfor %}        
    </a>
        
    {% endif%}

    <!-- 할것
    1. 유저가 팀 있을시 마이팀 표시 제일 위에
    2. 팀 리스트에서 팀 목록 가져와서 하나씩 표시
    2-1. 유저가 가입 팀이 없을 경우
    2-1-1 유저가 신청 팀이 없을 경우 : 팀 목록 옆에 신청 버튼 표시
    2-1-2 유저가 신청 팀이 있는 경우 : 팀 목록 옆에 신청 버튼 없음
    -->

    {% for team in team_list %}
    {% if team.team_name != user_team %}
        <a class="list-group-item list-group-item-action" style="display: flex; align-items: center; justify-content: space-between;">
            <div>
                <b>{{ team.team_name|truncatewords:5 }}</b>
                <li>팀장 : {{ team.team_manager }}</li>
            </div>
            <div style="margin-left: auto; display: flex; gap: 10px;">
                {% if login %}
                    {% if user_team == None %}
                        {% if user_request_to != None %}
                            {% if user_request_to == team.team_name %}
                                <form method="post" action="{% url 'team_calendar:cancel_request' %}" class="mt-2">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-warning btn-sm"><b>요청 취소</b></button>
                                </form>
                            {% endif %}
                        {% else %}
                            <form method="post" action="{% url 'team_calendar:join_team' team.team_name %}" class="mt-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-sm"><b>가입 요청</b></button>
                            </form>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </a>
    {% endif %}
    {% empty %}
        <b>등록된 팀이 없습니다.</b>
    {% endfor%}

</div>
{% endblock contents%}


